<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DunglasBundleCarRentalBundleEntityRentingProxy extends \Dunglas\Bundle\CarRentalBundle\Entity\Renting implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function isActive()
    {
        $this->__load();
        return parent::isActive();
    }

    public function setCustomer(\Dunglas\Bundle\CarRentalBundle\Entity\Customer $customer)
    {
        $this->__load();
        return parent::setCustomer($customer);
    }

    public function getCustomer()
    {
        $this->__load();
        return parent::getCustomer();
    }

    public function setVehicle(\Dunglas\Bundle\CarRentalBundle\Entity\Vehicle $vehicle)
    {
        $this->__load();
        return parent::setVehicle($vehicle);
    }

    public function getVehicle()
    {
        $this->__load();
        return parent::getVehicle();
    }

    public function addPayments(\Dunglas\Bundle\CarRentalBundle\Entity\Payment $payments)
    {
        $this->__load();
        return parent::addPayments($payments);
    }

    public function getPayments()
    {
        $this->__load();
        return parent::getPayments();
    }

    public function setExited($exited)
    {
        $this->__load();
        return parent::setExited($exited);
    }

    public function getExited()
    {
        $this->__load();
        return parent::getExited();
    }

    public function setScheduledReturn($scheduledReturn)
    {
        $this->__load();
        return parent::setScheduledReturn($scheduledReturn);
    }

    public function getScheduledReturn()
    {
        $this->__load();
        return parent::getScheduledReturn();
    }

    public function setReturned($returned)
    {
        $this->__load();
        return parent::setReturned($returned);
    }

    public function getReturned()
    {
        $this->__load();
        return parent::getReturned();
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addPayment(\Dunglas\Bundle\CarRentalBundle\Entity\Payment $payments)
    {
        $this->__load();
        return parent::addPayment($payments);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'customer', 'vehicle', 'exited', 'scheduledReturn', 'returned', 'notes', 'active', 'payments', 'created', 'updated');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}