<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DunglasBundleCarRentalBundleEntityVehicleProxy extends \Dunglas\Bundle\CarRentalBundle\Entity\Vehicle implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumberPlate($numberPlate)
    {
        $this->__load();
        return parent::setNumberPlate($numberPlate);
    }

    public function getNumberPlate()
    {
        $this->__load();
        return parent::getNumberPlate();
    }

    public function setVersion($version)
    {
        $this->__load();
        return parent::setVersion($version);
    }

    public function getVersion()
    {
        $this->__load();
        return parent::getVersion();
    }

    public function setNextVehicleInspection($nextVehicleInspection)
    {
        $this->__load();
        return parent::setNextVehicleInspection($nextVehicleInspection);
    }

    public function getNextVehicleInspection()
    {
        $this->__load();
        return parent::getNextVehicleInspection();
    }

    public function setLastValvetrain($lastValvetrain)
    {
        $this->__load();
        return parent::setLastValvetrain($lastValvetrain);
    }

    public function getLastValvetrain()
    {
        $this->__load();
        return parent::getLastValvetrain();
    }

    public function setValvetrain($valvetrain)
    {
        $this->__load();
        return parent::setValvetrain($valvetrain);
    }

    public function getValvetrain()
    {
        $this->__load();
        return parent::getValvetrain();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function addRentals(\Dunglas\Bundle\CarRentalBundle\Entity\Renting $rentals)
    {
        $this->__load();
        return parent::addRentals($rentals);
    }

    public function getRentals()
    {
        $this->__load();
        return parent::getRentals();
    }

    public function addMaintenances(\Dunglas\Bundle\CarRentalBundle\Entity\Maintenance $maintenances)
    {
        $this->__load();
        return parent::addMaintenances($maintenances);
    }

    public function getMaintenances()
    {
        $this->__load();
        return parent::getMaintenances();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setModel(\Dunglas\Bundle\CarRentalBundle\Entity\Model $model)
    {
        $this->__load();
        return parent::setModel($model);
    }

    public function getModel()
    {
        $this->__load();
        return parent::getModel();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setFuel(\Dunglas\Bundle\CarRentalBundle\Entity\Fuel $fuel)
    {
        $this->__load();
        return parent::setFuel($fuel);
    }

    public function getFuel()
    {
        $this->__load();
        return parent::getFuel();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numberPlate', 'model', 'version', 'fuel', 'nextVehicleInspection', 'lastValvetrain', 'valvetrain', 'notes', 'active', 'rentals', 'maintenances', 'created', 'updated');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}